### ISSUE TITLE
npm readme is off

### ISSUE THREAD

**Issue by MickL** [fwalzel/handlebars-i18n#2]
Took me some hours to figure out the reade in npm is off: It tells one to install the package `handlebars-i18next` instead of `handlebars-i18n`.

Btw. the readme has a typo and often says "handelbars" instead of "handlebars"

**Comment by fwalzel** [comment]
Hi, 
thanks for the ticket. I will fix that.

Sincerely, Florian

**Comment by fwalzel** [comment]
okay, it's fixed by now

**Comment by dargmuesli** [comment]
At least for me the README **on NPM** is still outdated. Could be related to the failing CI builds? npm authentication goes wrong...
