### ISSUE TITLE
document how to change language base on user setting

### ISSUE THREAD

**Issue by javadbat** [fwalzel/handlebars-i18n#20]
first of all, thank you for your effort you put to maintain this repo its help me a lot
my question is how can I change the render language base on the user setting?
in our project, we keep user language in our cookie, and in every request, we get it like this:
![image](https://user-images.githubusercontent.com/11534875/115156887-c88d2380-a09b-11eb-9812-77fd1b00bbc4.png)
my question is how I can tell the handlebar to render the page base on lang variable
thank you.

**Comment by javadbat** [comment]
to make my problem clear my current solution is this:
![image](https://user-images.githubusercontent.com/11534875/115157372-24f14280-a09e-11eb-98ba-8d31c62926d6.png)
but as I think set ` i18next.changeLanguage(lang);` is not a good idea because my whole node application language change on every request and it's CRAZY! I just want that specific request handled and rendered in lang and I don't want to change my  entire i18n config for each request

**Comment by andremetzen** [comment]
@fwalzel I'm also having the same issue but on a different context (too long to explain here). The main issue here is that we can have multiple instance of i18next but handlebars-i18n always assume the instance getting it from [`require('i18next')` here](https://github.com/Aller-Couleur/handlebars-i18n/blob/master/dist/handlebars-i18n.js#L39). 

My suggestion is to allow override it passing the `i18next` instance to `init()` method.

**Comment by fwalzel** [comment]
Feature is now ready in v1.3.0. See readme.md under "Using custom instances of Handlebars"
